BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "section" (
	"id"	INTEGER,
	"name"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "items" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL DEFAULT 'No Name' UNIQUE,
	"filePath"	TEXT NOT NULL,
	"fileType"	TEXT NOT NULL,
	"sectionId"	INTEGER NOT NULL,
	FOREIGN KEY("sectionId") REFERENCES "section"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
